import socket

#orice nu e comentat a se intelege ca sunt niste setari care asa se cer facute
dhcp_discover = {
    'op': b'01', #message type = 1 => DHCPDISCOVER
    'htype': b'01',
    'hlen': b'06',
    'hops': b'00',
    'xid': b'37a548a1', #transaction identifier generated by client : punem si noi un nr acolo
    'secs': b'0000',
    'flags': b'8000',
    'ciaddr': b'00000000',
    'yiaddr': b'00000000',
    'siaddr': b'00000000',
    'giaddr': b'00000000',
    'chaddr': b'8125f59fefac00000000000000000000',
    'sname': b'00' * 64,
    'file': b'00' * 128,
    'magic cookie': b'63825363',
    'options': b'350101' +  #option 53 : message type  = discover ; code = 35 (53 in decimal), length = 01 = 1 octet (adica 2 litere in hexa) , 01 e valoarea (dhcp discover)
               b'3d078125f59fefac54' +  #optiunea 61 : Client Identifier : mostly the chaddr + alte numere;
               b'3204c0a80075' +  # option 50 : se cere o adresa ip specifica
               b'0c09466c6f72696e2d5043' + #The laptop's name, option 12
               b'370c010f0306021c1f2179f92b' +  #optiunea 55 parameter request = lista de coduri cu optiunile cerute de client, aici spre exemplu e 1,15,3,6,2,28....
               b'ff'  #endmark
}

#functie ajutatoare pentru debug
def dict_to_bytes(message):
    rez = b''
    for key, val in message.items():
        rez += message[key]
    return rez

client_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
client_socket.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
client_socket.bind(('0.0.0.0', 68))
print("\nC:About to send a discover message")
client_socket.sendto(dict_to_bytes(dhcp_discover), ('255.255.255.255', 67))
print("\nDHCPDISCOVER sent")

data = client_socket.recvfrom(300)
print("C: Received this thing : " + data[0].decode('utf-8'))

print("\nC:About to send a request message")
client_socket.sendto(b'Request msg broooo', ('255.255.255.255', 67))
print("\nDHCPREQUEST sent")


